import { Summary } from './summary.service.model';

export const summaries: Summary[] = [
    {
        allowedRole: 'customer',
        titleKey: 'DashboardPage.summary.activeOrder.title',
        emoji: '📋',
        quantity: 2,
        unitType: null,
        colorType: 'blue',
    },
    {
        allowedRole: 'customer',
        titleKey: 'DashboardPage.summary.totalArea.title',
        emoji: '🌾',
        quantity: 145,
        unitType: 'hectare',
        colorType: 'green',
    },
    {
        allowedRole: 'customer',
        titleKey: 'DashboardPage.summary.spending.title',
        emoji: '💰',
        quantity: 126000,
        unitType: 'money',
        colorType: 'purple',
    },
    {
        allowedRole: 'customer',
        titleKey: 'DashboardPage.summary.pending.title',
        emoji: '⏳',
        quantity: 3,
        unitType: null,
        colorType: 'yellow',
    },
    {
        allowedRole: 'pilot',
        titleKey: 'DashboardPage.summary.assignedMissions',
        emoji: '🎯',
        quantity: 2,
        unitType: null,
        colorType: 'blue',
    },
    {
        allowedRole: 'pilot',
        titleKey: 'DashboardPage.summary.completed',
        emoji: '✅',
        quantity: 8,
        unitType: null,
        colorType: 'green',
    },
    {
        allowedRole: 'pilot',
        titleKey: 'DashboardPage.summary.flight.title',
        emoji: '🚁',
        quantity: 47.5,
        unitType: 'hour',
        colorType: 'purple',
    },
    {
        allowedRole: 'pilot',
        titleKey: 'DashboardPage.summary.performance.title',
        emoji: '⭐',
        quantity: 4.8,
        unitType: 'rating',
        colorType: 'yellow',
    },
    {
        allowedRole: 'office',
        titleKey: 'DashboardPage.summary.activeMission.title',
        emoji: '🎮',
        quantity: 12,
        unitType: null,
        colorType: 'blue',
    },
    {
        allowedRole: 'office',
        titleKey: 'DashboardPage.summary.availablePilots.title',
        emoji: '👨‍✈️',
        quantity: 5,
        unitType: null,
        colorType: 'green',
    },
    {
        allowedRole: 'office',
        titleKey: 'DashboardPage.summary.unassigned.title',
        emoji: '⚠️',
        quantity: 3,
        unitType: null,
        colorType: 'red',
    },
    {
        allowedRole: 'office',
        titleKey: 'DashboardPage.summary.revenue.title',
        emoji: '💼',
        quantity: 12450,
        unitType: 'money',
        colorType: 'purple',
    },
];
