name: Angular Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  angular:
    name: Angular Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      # Step 1: Checkout the source code
      - name: Checkout the source code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run ESLint
      - name: Run ESLint
        run: npm run lint

      # Step 5: Run Stylelint
      - name: Run Stylelint
        run: npm run stylelint

      # Step 6: Run Prettier Fix
      - name: Run Prettier
        run: npm run prettier:fix

      # Step 7: Run tests
      - name: Run test:ci
        run: npm run test

      # Step 8: Build the Angular application
      - name: Build
        run: npm run build
